// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: login.proto

package loginservice

import (
	"context"

	"zerogame/pb/login"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BanUserRequest           = login.BanUserRequest
	BanUserResponse          = login.BanUserResponse
	BindQueryRequest         = login.BindQueryRequest
	BindQueryResponse        = login.BindQueryResponse
	CheckUserStatusRequest   = login.CheckUserStatusRequest
	CheckUserStatusResponse  = login.CheckUserStatusResponse
	CurrentGameQueryRequest  = login.CurrentGameQueryRequest
	CurrentGameQueryResponse = login.CurrentGameQueryResponse
	LogonRequest             = login.LogonRequest
	LogonResponse            = login.LogonResponse
	PasswordResetRequest     = login.PasswordResetRequest
	PasswordResetResponse    = login.PasswordResetResponse
	RegisterRequest          = login.RegisterRequest
	RegisterResponse         = login.RegisterResponse
	VerifyCodeRequest        = login.VerifyCodeRequest
	VerifyCodeResponse       = login.VerifyCodeResponse

	LoginService interface {
		// 登录
		Logon(ctx context.Context, in *LogonRequest, opts ...grpc.CallOption) (*LogonResponse, error)
		// 注册
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		// 密码重置
		ResetPassword(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*PasswordResetResponse, error)
		// 获取验证码
		SendVerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error)
		// 账号绑定查询
		BindQuery(ctx context.Context, in *BindQueryRequest, opts ...grpc.CallOption) (*BindQueryResponse, error)
		// 查询玩家当前游戏
		CurrentGameQuery(ctx context.Context, in *CurrentGameQueryRequest, opts ...grpc.CallOption) (*CurrentGameQueryResponse, error)
		// 检查用户状态
		CheckUserStatus(ctx context.Context, in *CheckUserStatusRequest, opts ...grpc.CallOption) (*CheckUserStatusResponse, error)
		// 封禁用户
		BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*BanUserResponse, error)
	}

	defaultLoginService struct {
		cli zrpc.Client
	}
)

func NewLoginService(cli zrpc.Client) LoginService {
	return &defaultLoginService{
		cli: cli,
	}
}

// 登录
func (m *defaultLoginService) Logon(ctx context.Context, in *LogonRequest, opts ...grpc.CallOption) (*LogonResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.Logon(ctx, in, opts...)
}

// 注册
func (m *defaultLoginService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 密码重置
func (m *defaultLoginService) ResetPassword(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*PasswordResetResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

// 获取验证码
func (m *defaultLoginService) SendVerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.SendVerifyCode(ctx, in, opts...)
}

// 账号绑定查询
func (m *defaultLoginService) BindQuery(ctx context.Context, in *BindQueryRequest, opts ...grpc.CallOption) (*BindQueryResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.BindQuery(ctx, in, opts...)
}

// 查询玩家当前游戏
func (m *defaultLoginService) CurrentGameQuery(ctx context.Context, in *CurrentGameQueryRequest, opts ...grpc.CallOption) (*CurrentGameQueryResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.CurrentGameQuery(ctx, in, opts...)
}

// 检查用户状态
func (m *defaultLoginService) CheckUserStatus(ctx context.Context, in *CheckUserStatusRequest, opts ...grpc.CallOption) (*CheckUserStatusResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.CheckUserStatus(ctx, in, opts...)
}

// 封禁用户
func (m *defaultLoginService) BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*BanUserResponse, error) {
	client := login.NewLoginServiceClient(m.cli.Conn())
	return client.BanUser(ctx, in, opts...)
}
