// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Accounts string `json:"accounts"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
