// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: login.proto

package server

import (
	"context"

	"zerogame/pb/login"
	"zerogame/server/login/internal/logic"
	"zerogame/server/login/internal/svc"
)

type LoginServiceServer struct {
	svcCtx *svc.ServiceContext
	login.UnimplementedLoginServiceServer
}

func NewLoginServiceServer(svcCtx *svc.ServiceContext) *LoginServiceServer {
	return &LoginServiceServer{
		svcCtx: svcCtx,
	}
}

// 登录
func (s *LoginServiceServer) Logon(ctx context.Context, in *login.LogonRequest) (*login.LogonResponse, error) {
	l := logic.NewLogonLogic(ctx, s.svcCtx)
	return l.Logon(in)
}

// 注册
func (s *LoginServiceServer) Register(ctx context.Context, in *login.RegisterRequest) (*login.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 密码重置
func (s *LoginServiceServer) ResetPassword(ctx context.Context, in *login.PasswordResetRequest) (*login.PasswordResetResponse, error) {
	l := logic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}

// 获取验证码
func (s *LoginServiceServer) SendVerifyCode(ctx context.Context, in *login.VerifyCodeRequest) (*login.VerifyCodeResponse, error) {
	l := logic.NewSendVerifyCodeLogic(ctx, s.svcCtx)
	return l.SendVerifyCode(in)
}

// 账号绑定查询
func (s *LoginServiceServer) BindQuery(ctx context.Context, in *login.BindQueryRequest) (*login.BindQueryResponse, error) {
	l := logic.NewBindQueryLogic(ctx, s.svcCtx)
	return l.BindQuery(in)
}

// 查询玩家当前游戏
func (s *LoginServiceServer) CurrentGameQuery(ctx context.Context, in *login.CurrentGameQueryRequest) (*login.CurrentGameQueryResponse, error) {
	l := logic.NewCurrentGameQueryLogic(ctx, s.svcCtx)
	return l.CurrentGameQuery(in)
}

// 检查用户状态
func (s *LoginServiceServer) CheckUserStatus(ctx context.Context, in *login.CheckUserStatusRequest) (*login.CheckUserStatusResponse, error) {
	l := logic.NewCheckUserStatusLogic(ctx, s.svcCtx)
	return l.CheckUserStatus(in)
}

// 封禁用户
func (s *LoginServiceServer) BanUser(ctx context.Context, in *login.BanUserRequest) (*login.BanUserResponse, error) {
	l := logic.NewBanUserLogic(ctx, s.svcCtx)
	return l.BanUser(in)
}
