// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/login.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      string                 `protobuf:"bytes,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 0游客 1账号 5手机 6邮箱 7TG
	SysVersion    string                 `protobuf:"bytes,4,opt,name=sys_version,json=sysVersion,proto3" json:"sys_version,omitempty"`
	Models        string                 `protobuf:"bytes,5,opt,name=models,proto3" json:"models,omitempty"`
	Channel       string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	Versions      string                 `protobuf:"bytes,8,opt,name=versions,proto3" json:"versions,omitempty"`
	Location      string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Token         string                 `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`
	ShopId        int32                  `protobuf:"varint,11,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	DeviceModel   string                 `protobuf:"bytes,12,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	Gps           string                 `protobuf:"bytes,13,opt,name=gps,proto3" json:"gps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogonRequest) Reset() {
	*x = LogonRequest{}
	mi := &file_proto_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogonRequest) ProtoMessage() {}

func (x *LogonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogonRequest.ProtoReflect.Descriptor instead.
func (*LogonRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{0}
}

func (x *LogonRequest) GetAccounts() string {
	if x != nil {
		return x.Accounts
	}
	return ""
}

func (x *LogonRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LogonRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LogonRequest) GetSysVersion() string {
	if x != nil {
		return x.SysVersion
	}
	return ""
}

func (x *LogonRequest) GetModels() string {
	if x != nil {
		return x.Models
	}
	return ""
}

func (x *LogonRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *LogonRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LogonRequest) GetVersions() string {
	if x != nil {
		return x.Versions
	}
	return ""
}

func (x *LogonRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LogonRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LogonRequest) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *LogonRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *LogonRequest) GetGps() string {
	if x != nil {
		return x.Gps
	}
	return ""
}

type LogonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ConfineTime   string                 `protobuf:"bytes,3,opt,name=confine_time,json=confineTime,proto3" json:"confine_time,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Skin          string                 `protobuf:"bytes,5,opt,name=skin,proto3" json:"skin,omitempty"`
	UiType        string                 `protobuf:"bytes,6,opt,name=ui_type,json=uiType,proto3" json:"ui_type,omitempty"`
	Versions      string                 `protobuf:"bytes,7,opt,name=versions,proto3" json:"versions,omitempty"`
	LoginCount    int32                  `protobuf:"varint,8,opt,name=login_count,json=loginCount,proto3" json:"login_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogonResponse) Reset() {
	*x = LogonResponse{}
	mi := &file_proto_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogonResponse) ProtoMessage() {}

func (x *LogonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogonResponse.ProtoReflect.Descriptor instead.
func (*LogonResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{1}
}

func (x *LogonResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogonResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *LogonResponse) GetConfineTime() string {
	if x != nil {
		return x.ConfineTime
	}
	return ""
}

func (x *LogonResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LogonResponse) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

func (x *LogonResponse) GetUiType() string {
	if x != nil {
		return x.UiType
	}
	return ""
}

func (x *LogonResponse) GetVersions() string {
	if x != nil {
		return x.Versions
	}
	return ""
}

func (x *LogonResponse) GetLoginCount() int32 {
	if x != nil {
		return x.LoginCount
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      string                 `protobuf:"bytes,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex           int32                  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	SysVersion    string                 `protobuf:"bytes,5,opt,name=sys_version,json=sysVersion,proto3" json:"sys_version,omitempty"`
	Models        string                 `protobuf:"bytes,6,opt,name=models,proto3" json:"models,omitempty"`
	Channel       string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	PhoneType     string                 `protobuf:"bytes,9,opt,name=phone_type,json=phoneType,proto3" json:"phone_type,omitempty"`
	Platform      string                 `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`
	Versions      string                 `protobuf:"bytes,11,opt,name=versions,proto3" json:"versions,omitempty"`
	Location      string                 `protobuf:"bytes,12,opt,name=location,proto3" json:"location,omitempty"`
	ShopId        int32                  `protobuf:"varint,13,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	FaceId        string                 `protobuf:"bytes,14,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	RegisterWay   int32                  `protobuf:"varint,15,opt,name=register_way,json=registerWay,proto3" json:"register_way,omitempty"` // 5手机 6邮箱
	VerifyCode    string                 `protobuf:"bytes,16,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAccounts() string {
	if x != nil {
		return x.Accounts
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *RegisterRequest) GetSysVersion() string {
	if x != nil {
		return x.SysVersion
	}
	return ""
}

func (x *RegisterRequest) GetModels() string {
	if x != nil {
		return x.Models
	}
	return ""
}

func (x *RegisterRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetPhoneType() string {
	if x != nil {
		return x.PhoneType
	}
	return ""
}

func (x *RegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterRequest) GetVersions() string {
	if x != nil {
		return x.Versions
	}
	return ""
}

func (x *RegisterRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RegisterRequest) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *RegisterRequest) GetFaceId() string {
	if x != nil {
		return x.FaceId
	}
	return ""
}

func (x *RegisterRequest) GetRegisterWay() int32 {
	if x != nil {
		return x.RegisterWay
	}
	return 0
}

func (x *RegisterRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Skin          string                 `protobuf:"bytes,3,opt,name=skin,proto3" json:"skin,omitempty"`
	UiType        string                 `protobuf:"bytes,4,opt,name=ui_type,json=uiType,proto3" json:"ui_type,omitempty"`
	Versions      string                 `protobuf:"bytes,5,opt,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *RegisterResponse) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

func (x *RegisterResponse) GetUiType() string {
	if x != nil {
		return x.UiType
	}
	return ""
}

func (x *RegisterResponse) GetVersions() string {
	if x != nil {
		return x.Versions
	}
	return ""
}

type VerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Way           int32                  `protobuf:"varint,1,opt,name=way,proto3" json:"way,omitempty"` // 5手机 6邮箱
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Purpose       int32                  `protobuf:"varint,3,opt,name=purpose,proto3" json:"purpose,omitempty"` // 0注册 1重置密码
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	mi := &file_proto_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyCodeRequest) GetWay() int32 {
	if x != nil {
		return x.Way
	}
	return 0
}

func (x *VerifyCodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VerifyCodeRequest) GetPurpose() int32 {
	if x != nil {
		return x.Purpose
	}
	return 0
}

func (x *VerifyCodeRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type VerifyCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Way           int32                  `protobuf:"varint,2,opt,name=way,proto3" json:"way,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeResponse) Reset() {
	*x = VerifyCodeResponse{}
	mi := &file_proto_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeResponse) ProtoMessage() {}

func (x *VerifyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyCodeResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *VerifyCodeResponse) GetWay() int32 {
	if x != nil {
		return x.Way
	}
	return 0
}

type PasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Way           int32                  `protobuf:"varint,1,opt,name=way,proto3" json:"way,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetRequest) Reset() {
	*x = PasswordResetRequest{}
	mi := &file_proto_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetRequest) ProtoMessage() {}

func (x *PasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetRequest.ProtoReflect.Descriptor instead.
func (*PasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{6}
}

func (x *PasswordResetRequest) GetWay() int32 {
	if x != nil {
		return x.Way
	}
	return 0
}

func (x *PasswordResetRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PasswordResetRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *PasswordResetRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type PasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetResponse) Reset() {
	*x = PasswordResetResponse{}
	mi := &file_proto_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetResponse) ProtoMessage() {}

func (x *PasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetResponse.ProtoReflect.Descriptor instead.
func (*PasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{7}
}

func (x *PasswordResetResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type BindQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindQueryRequest) Reset() {
	*x = BindQueryRequest{}
	mi := &file_proto_login_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindQueryRequest) ProtoMessage() {}

func (x *BindQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindQueryRequest.ProtoReflect.Descriptor instead.
func (*BindQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{8}
}

func (x *BindQueryRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type BindQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 0无 1手机 2邮箱 3都有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindQueryResponse) Reset() {
	*x = BindQueryResponse{}
	mi := &file_proto_login_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindQueryResponse) ProtoMessage() {}

func (x *BindQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindQueryResponse.ProtoReflect.Descriptor instead.
func (*BindQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{9}
}

func (x *BindQueryResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CurrentGameQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentGameQueryRequest) Reset() {
	*x = CurrentGameQueryRequest{}
	mi := &file_proto_login_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentGameQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentGameQueryRequest) ProtoMessage() {}

func (x *CurrentGameQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentGameQueryRequest.ProtoReflect.Descriptor instead.
func (*CurrentGameQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{10}
}

func (x *CurrentGameQueryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CurrentGameQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	TableId       string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentGameQueryResponse) Reset() {
	*x = CurrentGameQueryResponse{}
	mi := &file_proto_login_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentGameQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentGameQueryResponse) ProtoMessage() {}

func (x *CurrentGameQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentGameQueryResponse.ProtoReflect.Descriptor instead.
func (*CurrentGameQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{11}
}

func (x *CurrentGameQueryResponse) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CurrentGameQueryResponse) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type CheckUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserStatusRequest) Reset() {
	*x = CheckUserStatusRequest{}
	mi := &file_proto_login_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserStatusRequest) ProtoMessage() {}

func (x *CheckUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{12}
}

func (x *CheckUserStatusRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBanned      bool                   `protobuf:"varint,1,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserStatusResponse) Reset() {
	*x = CheckUserStatusResponse{}
	mi := &file_proto_login_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserStatusResponse) ProtoMessage() {}

func (x *CheckUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{13}
}

func (x *CheckUserStatusResponse) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *CheckUserStatusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BanUserRequest) Reset() {
	*x = BanUserRequest{}
	mi := &file_proto_login_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserRequest) ProtoMessage() {}

func (x *BanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserRequest.ProtoReflect.Descriptor instead.
func (*BanUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{14}
}

func (x *BanUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BanUserRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *BanUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserResponse) Reset() {
	*x = BanUserResponse{}
	mi := &file_proto_login_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserResponse) ProtoMessage() {}

func (x *BanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserResponse.ProtoReflect.Descriptor instead.
func (*BanUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{15}
}

var File_proto_login_proto protoreflect.FileDescriptor

const file_proto_login_proto_rawDesc = "" +
	"\n" +
	"\x11proto/login.proto\x12\vproto.login\"\xe5\x02\n" +
	"\fLogonRequest\x12\x1a\n" +
	"\baccounts\x18\x01 \x01(\tR\baccounts\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x1f\n" +
	"\vsys_version\x18\x04 \x01(\tR\n" +
	"sysVersion\x12\x16\n" +
	"\x06models\x18\x05 \x01(\tR\x06models\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\x12\x1a\n" +
	"\bversions\x18\b \x01(\tR\bversions\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x14\n" +
	"\x05token\x18\n" +
	" \x01(\tR\x05token\x12\x17\n" +
	"\ashop_id\x18\v \x01(\x05R\x06shopId\x12!\n" +
	"\fdevice_model\x18\f \x01(\tR\vdeviceModel\x12\x10\n" +
	"\x03gps\x18\r \x01(\tR\x03gps\"\xea\x01\n" +
	"\rLogonResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12!\n" +
	"\fconfine_time\x18\x03 \x01(\tR\vconfineTime\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x12\n" +
	"\x04skin\x18\x05 \x01(\tR\x04skin\x12\x17\n" +
	"\aui_type\x18\x06 \x01(\tR\x06uiType\x12\x1a\n" +
	"\bversions\x18\a \x01(\tR\bversions\x12\x1f\n" +
	"\vlogin_count\x18\b \x01(\x05R\n" +
	"loginCount\"\xc3\x03\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\baccounts\x18\x01 \x01(\tR\baccounts\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\x05R\x03sex\x12\x1f\n" +
	"\vsys_version\x18\x05 \x01(\tR\n" +
	"sysVersion\x12\x16\n" +
	"\x06models\x18\x06 \x01(\tR\x06models\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"phone_type\x18\t \x01(\tR\tphoneType\x12\x1a\n" +
	"\bplatform\x18\n" +
	" \x01(\tR\bplatform\x12\x1a\n" +
	"\bversions\x18\v \x01(\tR\bversions\x12\x1a\n" +
	"\blocation\x18\f \x01(\tR\blocation\x12\x17\n" +
	"\ashop_id\x18\r \x01(\x05R\x06shopId\x12\x17\n" +
	"\aface_id\x18\x0e \x01(\tR\x06faceId\x12!\n" +
	"\fregister_way\x18\x0f \x01(\x05R\vregisterWay\x12\x1f\n" +
	"\vverify_code\x18\x10 \x01(\tR\n" +
	"verifyCode\"\x93\x01\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12\x12\n" +
	"\x04skin\x18\x03 \x01(\tR\x04skin\x12\x17\n" +
	"\aui_type\x18\x04 \x01(\tR\x06uiType\x12\x1a\n" +
	"\bversions\x18\x05 \x01(\tR\bversions\"s\n" +
	"\x11VerifyCodeRequest\x12\x10\n" +
	"\x03way\x18\x01 \x01(\x05R\x03way\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\x05R\apurpose\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\">\n" +
	"\x12VerifyCodeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x10\n" +
	"\x03way\x18\x02 \x01(\x05R\x03way\"\x86\x01\n" +
	"\x14PasswordResetRequest\x12\x10\n" +
	"\x03way\x18\x01 \x01(\x05R\x03way\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\x12!\n" +
	"\fnew_password\x18\x04 \x01(\tR\vnewPassword\"/\n" +
	"\x15PasswordResetResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\",\n" +
	"\x10BindQueryRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"+\n" +
	"\x11BindQueryResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"2\n" +
	"\x17CurrentGameQueryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"N\n" +
	"\x18CurrentGameQueryResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x05R\x06gameId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\"1\n" +
	"\x16CheckUserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"N\n" +
	"\x17CheckUserStatusResponse\x12\x1b\n" +
	"\tis_banned\x18\x01 \x01(\bR\bisBanned\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"l\n" +
	"\x0eBanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x11\n" +
	"\x0fBanUserResponse2\x93\x05\n" +
	"\fLoginService\x12>\n" +
	"\x05Logon\x12\x19.proto.login.LogonRequest\x1a\x1a.proto.login.LogonResponse\x12G\n" +
	"\bRegister\x12\x1c.proto.login.RegisterRequest\x1a\x1d.proto.login.RegisterResponse\x12V\n" +
	"\rResetPassword\x12!.proto.login.PasswordResetRequest\x1a\".proto.login.PasswordResetResponse\x12Q\n" +
	"\x0eSendVerifyCode\x12\x1e.proto.login.VerifyCodeRequest\x1a\x1f.proto.login.VerifyCodeResponse\x12J\n" +
	"\tBindQuery\x12\x1d.proto.login.BindQueryRequest\x1a\x1e.proto.login.BindQueryResponse\x12_\n" +
	"\x10CurrentGameQuery\x12$.proto.login.CurrentGameQueryRequest\x1a%.proto.login.CurrentGameQueryResponse\x12\\\n" +
	"\x0fCheckUserStatus\x12#.proto.login.CheckUserStatusRequest\x1a$.proto.login.CheckUserStatusResponse\x12D\n" +
	"\aBanUser\x12\x1b.proto.login.BanUserRequest\x1a\x1c.proto.login.BanUserResponseB\tZ\a./loginb\x06proto3"

var (
	file_proto_login_proto_rawDescOnce sync.Once
	file_proto_login_proto_rawDescData []byte
)

func file_proto_login_proto_rawDescGZIP() []byte {
	file_proto_login_proto_rawDescOnce.Do(func() {
		file_proto_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)))
	})
	return file_proto_login_proto_rawDescData
}

var file_proto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_login_proto_goTypes = []any{
	(*LogonRequest)(nil),             // 0: proto.login.LogonRequest
	(*LogonResponse)(nil),            // 1: proto.login.LogonResponse
	(*RegisterRequest)(nil),          // 2: proto.login.RegisterRequest
	(*RegisterResponse)(nil),         // 3: proto.login.RegisterResponse
	(*VerifyCodeRequest)(nil),        // 4: proto.login.VerifyCodeRequest
	(*VerifyCodeResponse)(nil),       // 5: proto.login.VerifyCodeResponse
	(*PasswordResetRequest)(nil),     // 6: proto.login.PasswordResetRequest
	(*PasswordResetResponse)(nil),    // 7: proto.login.PasswordResetResponse
	(*BindQueryRequest)(nil),         // 8: proto.login.BindQueryRequest
	(*BindQueryResponse)(nil),        // 9: proto.login.BindQueryResponse
	(*CurrentGameQueryRequest)(nil),  // 10: proto.login.CurrentGameQueryRequest
	(*CurrentGameQueryResponse)(nil), // 11: proto.login.CurrentGameQueryResponse
	(*CheckUserStatusRequest)(nil),   // 12: proto.login.CheckUserStatusRequest
	(*CheckUserStatusResponse)(nil),  // 13: proto.login.CheckUserStatusResponse
	(*BanUserRequest)(nil),           // 14: proto.login.BanUserRequest
	(*BanUserResponse)(nil),          // 15: proto.login.BanUserResponse
}
var file_proto_login_proto_depIdxs = []int32{
	0,  // 0: proto.login.LoginService.Logon:input_type -> proto.login.LogonRequest
	2,  // 1: proto.login.LoginService.Register:input_type -> proto.login.RegisterRequest
	6,  // 2: proto.login.LoginService.ResetPassword:input_type -> proto.login.PasswordResetRequest
	4,  // 3: proto.login.LoginService.SendVerifyCode:input_type -> proto.login.VerifyCodeRequest
	8,  // 4: proto.login.LoginService.BindQuery:input_type -> proto.login.BindQueryRequest
	10, // 5: proto.login.LoginService.CurrentGameQuery:input_type -> proto.login.CurrentGameQueryRequest
	12, // 6: proto.login.LoginService.CheckUserStatus:input_type -> proto.login.CheckUserStatusRequest
	14, // 7: proto.login.LoginService.BanUser:input_type -> proto.login.BanUserRequest
	1,  // 8: proto.login.LoginService.Logon:output_type -> proto.login.LogonResponse
	3,  // 9: proto.login.LoginService.Register:output_type -> proto.login.RegisterResponse
	7,  // 10: proto.login.LoginService.ResetPassword:output_type -> proto.login.PasswordResetResponse
	5,  // 11: proto.login.LoginService.SendVerifyCode:output_type -> proto.login.VerifyCodeResponse
	9,  // 12: proto.login.LoginService.BindQuery:output_type -> proto.login.BindQueryResponse
	11, // 13: proto.login.LoginService.CurrentGameQuery:output_type -> proto.login.CurrentGameQueryResponse
	13, // 14: proto.login.LoginService.CheckUserStatus:output_type -> proto.login.CheckUserStatusResponse
	15, // 15: proto.login.LoginService.BanUser:output_type -> proto.login.BanUserResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_login_proto_init() }
func file_proto_login_proto_init() {
	if File_proto_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_login_proto_goTypes,
		DependencyIndexes: file_proto_login_proto_depIdxs,
		MessageInfos:      file_proto_login_proto_msgTypes,
	}.Build()
	File_proto_login_proto = out.File
	file_proto_login_proto_goTypes = nil
	file_proto_login_proto_depIdxs = nil
}
