// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/websocket.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebSocket消息类型枚举
type MessageType int32

const (
	// 客户端消息类型
	MessageType_MSG_HEARTBEAT       MessageType = 0 // 心跳
	MessageType_MSG_LOGIN           MessageType = 1 // 登录
	MessageType_MSG_LOGOUT          MessageType = 2 // 登出
	MessageType_MSG_JOIN_ROOM       MessageType = 3 // 加入房间
	MessageType_MSG_LEAVE_ROOM      MessageType = 4 // 离开房间
	MessageType_MSG_GAME_ACTION     MessageType = 5 // 游戏操作
	MessageType_MSG_CHAT            MessageType = 6 // 聊天消息
	MessageType_MSG_USER_INFO_QUERY MessageType = 7 // 用户信息查询
	MessageType_MSG_ROOM_LIST_QUERY MessageType = 8 // 房间列表查询
	// 服务端推送消息类型
	MessageType_MSG_PUSH_GAME_STATE  MessageType = 100 // 游戏状态推送
	MessageType_MSG_PUSH_ROOM_INFO   MessageType = 101 // 房间信息推送
	MessageType_MSG_PUSH_USER_UPDATE MessageType = 102 // 用户状态更新
	MessageType_MSG_PUSH_SYSTEM_MSG  MessageType = 103 // 系统消息
	MessageType_MSG_PUSH_CHAT_MSG    MessageType = 104 // 聊天消息推送
	MessageType_MSG_PUSH_BROADCAST   MessageType = 105 // 广播消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MSG_HEARTBEAT",
		1:   "MSG_LOGIN",
		2:   "MSG_LOGOUT",
		3:   "MSG_JOIN_ROOM",
		4:   "MSG_LEAVE_ROOM",
		5:   "MSG_GAME_ACTION",
		6:   "MSG_CHAT",
		7:   "MSG_USER_INFO_QUERY",
		8:   "MSG_ROOM_LIST_QUERY",
		100: "MSG_PUSH_GAME_STATE",
		101: "MSG_PUSH_ROOM_INFO",
		102: "MSG_PUSH_USER_UPDATE",
		103: "MSG_PUSH_SYSTEM_MSG",
		104: "MSG_PUSH_CHAT_MSG",
		105: "MSG_PUSH_BROADCAST",
	}
	MessageType_value = map[string]int32{
		"MSG_HEARTBEAT":        0,
		"MSG_LOGIN":            1,
		"MSG_LOGOUT":           2,
		"MSG_JOIN_ROOM":        3,
		"MSG_LEAVE_ROOM":       4,
		"MSG_GAME_ACTION":      5,
		"MSG_CHAT":             6,
		"MSG_USER_INFO_QUERY":  7,
		"MSG_ROOM_LIST_QUERY":  8,
		"MSG_PUSH_GAME_STATE":  100,
		"MSG_PUSH_ROOM_INFO":   101,
		"MSG_PUSH_USER_UPDATE": 102,
		"MSG_PUSH_SYSTEM_MSG":  103,
		"MSG_PUSH_CHAT_MSG":    104,
		"MSG_PUSH_BROADCAST":   105,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_websocket_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_websocket_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{0}
}

// WebSocket消息头
type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       MessageType            `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=proto.websocket.MessageType" json:"msg_type,omitempty"` // 消息类型
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                         // 消息ID（用于请求响应配对）
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                             // 时间戳
	UserId        int32                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                     // 用户ID
	RoomId        string                 `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                      // 房间ID
	GameId        string                 `protobuf:"bytes,6,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                                      // 游戏ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_proto_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MSG_HEARTBEAT
}

func (x *MessageHeader) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MessageHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageHeader) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageHeader) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageHeader) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// WebSocket消息体
type WebSocketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"` // 消息体，根据消息类型解析为不同结构
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_proto_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *WebSocketMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WebSocketMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 心跳消息
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` // 客户端时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// 登录消息
type LoginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 登录token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginMessage) Reset() {
	*x = LoginMessage{}
	mi := &file_proto_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMessage) ProtoMessage() {}

func (x *LoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMessage.ProtoReflect.Descriptor instead.
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *LoginMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 登出消息
type LogoutMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutMessage) Reset() {
	*x = LogoutMessage{}
	mi := &file_proto_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutMessage) ProtoMessage() {}

func (x *LogoutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutMessage.ProtoReflect.Descriptor instead.
func (*LogoutMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{4}
}

// 加入房间消息
type JoinRoomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`           // 房间密码（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomMessage) Reset() {
	*x = JoinRoomMessage{}
	mi := &file_proto_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomMessage) ProtoMessage() {}

func (x *JoinRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomMessage.ProtoReflect.Descriptor instead.
func (*JoinRoomMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 离开房间消息
type LeaveRoomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomMessage) Reset() {
	*x = LeaveRoomMessage{}
	mi := &file_proto_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomMessage) ProtoMessage() {}

func (x *LeaveRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomMessage.ProtoReflect.Descriptor instead.
func (*LeaveRoomMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRoomMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 游戏操作消息
type GameActionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 操作类型
	ActionData    []byte                 `protobuf:"bytes,2,opt,name=action_data,json=actionData,proto3" json:"action_data,omitempty"` // 操作数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameActionMessage) Reset() {
	*x = GameActionMessage{}
	mi := &file_proto_websocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameActionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameActionMessage) ProtoMessage() {}

func (x *GameActionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameActionMessage.ProtoReflect.Descriptor instead.
func (*GameActionMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{7}
}

func (x *GameActionMessage) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *GameActionMessage) GetActionData() []byte {
	if x != nil {
		return x.ActionData
	}
	return nil
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatType      int32                  `protobuf:"varint,1,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"` // 聊天类型：0-世界 1-房间 2-私聊
	TargetId      int32                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID（私聊时使用）
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                    // 聊天内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_websocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessage) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *ChatMessage) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 用户信息查询
type UserInfoQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 查询的用户ID，0表示查询自己的信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoQuery) Reset() {
	*x = UserInfoQuery{}
	mi := &file_proto_websocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoQuery) ProtoMessage() {}

func (x *UserInfoQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoQuery.ProtoReflect.Descriptor instead.
func (*UserInfoQuery) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfoQuery) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 房间列表查询
type RoomListQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      string                 `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`  // 游戏类型
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListQuery) Reset() {
	*x = RoomListQuery{}
	mi := &file_proto_websocket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListQuery) ProtoMessage() {}

func (x *RoomListQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListQuery.ProtoReflect.Descriptor instead.
func (*RoomListQuery) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{10}
}

func (x *RoomListQuery) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *RoomListQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RoomListQuery) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 游戏状态推送
type GameStatePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`              // 房间ID
	GameStatus    int32                  `protobuf:"varint,2,opt,name=game_status,json=gameStatus,proto3" json:"game_status,omitempty"` // 游戏状态
	GameData      []byte                 `protobuf:"bytes,3,opt,name=game_data,json=gameData,proto3" json:"game_data,omitempty"`        // 游戏数据
	UpdateTime    int64                  `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStatePush) Reset() {
	*x = GameStatePush{}
	mi := &file_proto_websocket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStatePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatePush) ProtoMessage() {}

func (x *GameStatePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatePush.ProtoReflect.Descriptor instead.
func (*GameStatePush) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{11}
}

func (x *GameStatePush) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStatePush) GetGameStatus() int32 {
	if x != nil {
		return x.GameStatus
	}
	return 0
}

func (x *GameStatePush) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

func (x *GameStatePush) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 房间信息推送
type RoomInfoPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                 // 房间ID
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`           // 房间名称
	PlayerCount   int32                  `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"` // 玩家数量
	MaxPlayers    int32                  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`    // 最大玩家数
	RoomStatus    int32                  `protobuf:"varint,5,opt,name=room_status,json=roomStatus,proto3" json:"room_status,omitempty"`    // 房间状态
	RoomData      []byte                 `protobuf:"bytes,6,opt,name=room_data,json=roomData,proto3" json:"room_data,omitempty"`           // 房间数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfoPush) Reset() {
	*x = RoomInfoPush{}
	mi := &file_proto_websocket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfoPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoPush) ProtoMessage() {}

func (x *RoomInfoPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoPush.ProtoReflect.Descriptor instead.
func (*RoomInfoPush) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{12}
}

func (x *RoomInfoPush) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfoPush) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfoPush) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *RoomInfoPush) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfoPush) GetRoomStatus() int32 {
	if x != nil {
		return x.RoomStatus
	}
	return 0
}

func (x *RoomInfoPush) GetRoomData() []byte {
	if x != nil {
		return x.RoomData
	}
	return nil
}

// 用户状态更新推送
type UserUpdatePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                    // 用户状态
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`                 // 用户位置（房间ID等）
	UserData      []byte                 `protobuf:"bytes,4,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"` // 用户数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdatePush) Reset() {
	*x = UserUpdatePush{}
	mi := &file_proto_websocket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdatePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatePush) ProtoMessage() {}

func (x *UserUpdatePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatePush.ProtoReflect.Descriptor instead.
func (*UserUpdatePush) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{13}
}

func (x *UserUpdatePush) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdatePush) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserUpdatePush) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UserUpdatePush) GetUserData() []byte {
	if x != nil {
		return x.UserData
	}
	return nil
}

// 系统消息推送
type SystemMessagePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       int32                  `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`    // 消息类型
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                        // 标题
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                    // 内容
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"` // 过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMessagePush) Reset() {
	*x = SystemMessagePush{}
	mi := &file_proto_websocket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessagePush) ProtoMessage() {}

func (x *SystemMessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessagePush.ProtoReflect.Descriptor instead.
func (*SystemMessagePush) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{14}
}

func (x *SystemMessagePush) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SystemMessagePush) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SystemMessagePush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemMessagePush) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// 聊天消息推送
type ChatMessagePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`      // 发送者ID
	SenderName    string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"` // 发送者名称
	ChatType      int32                  `protobuf:"varint,3,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`      // 聊天类型
	TargetId      int32                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`      // 目标ID
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                         // 内容
	SendTime      int64                  `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`      // 发送时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessagePush) Reset() {
	*x = ChatMessagePush{}
	mi := &file_proto_websocket_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessagePush) ProtoMessage() {}

func (x *ChatMessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessagePush.ProtoReflect.Descriptor instead.
func (*ChatMessagePush) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{15}
}

func (x *ChatMessagePush) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessagePush) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMessagePush) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *ChatMessagePush) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ChatMessagePush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessagePush) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

// 广播消息
type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BroadcastId   string                 `protobuf:"bytes,1,opt,name=broadcast_id,json=broadcastId,proto3" json:"broadcast_id,omitempty"`        // 广播ID
	BroadcastType int32                  `protobuf:"varint,2,opt,name=broadcast_type,json=broadcastType,proto3" json:"broadcast_type,omitempty"` // 广播类型
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                       // 标题
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                   // 内容
	ExtraData     []byte                 `protobuf:"bytes,5,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`              // 额外数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_proto_websocket_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{16}
}

func (x *BroadcastMessage) GetBroadcastId() string {
	if x != nil {
		return x.BroadcastId
	}
	return ""
}

func (x *BroadcastMessage) GetBroadcastType() int32 {
	if x != nil {
		return x.BroadcastType
	}
	return 0
}

func (x *BroadcastMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BroadcastMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BroadcastMessage) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

// 通用响应消息
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`               // 响应码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                  // 响应消息
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                // 响应数据
	MsgId         string                 `protobuf:"bytes,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 对应的请求消息ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_proto_websocket_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{17}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CommonResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommonResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// 房间列表响应
type RoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`                              // 房间列表
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数量
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                               // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResponse) Reset() {
	*x = RoomListResponse{}
	mi := &file_proto_websocket_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResponse) ProtoMessage() {}

func (x *RoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResponse.ProtoReflect.Descriptor instead.
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{18}
}

func (x *RoomListResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *RoomListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RoomListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RoomListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                 // 房间ID
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`           // 房间名称
	GameType      string                 `protobuf:"bytes,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`           // 游戏类型
	PlayerCount   int32                  `protobuf:"varint,4,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"` // 当前玩家数
	MaxPlayers    int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`    // 最大玩家数
	RoomStatus    int32                  `protobuf:"varint,6,opt,name=room_status,json=roomStatus,proto3" json:"room_status,omitempty"`    // 房间状态
	CreateTime    string                 `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`     // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_proto_websocket_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{19}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *RoomInfo) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *RoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfo) GetRoomStatus() int32 {
	if x != nil {
		return x.RoomStatus
	}
	return 0
}

func (x *RoomInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

var File_proto_websocket_proto protoreflect.FileDescriptor

const file_proto_websocket_proto_rawDesc = "" +
	"\n" +
	"\x15proto/websocket.proto\x12\x0fproto.websocket\x1a\x12proto/common.proto\"\xc8\x01\n" +
	"\rMessageHeader\x127\n" +
	"\bmsg_type\x18\x01 \x01(\x0e2\x1c.proto.websocket.MessageTypeR\amsgType\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x05R\x06userId\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12\x17\n" +
	"\agame_id\x18\x06 \x01(\tR\x06gameId\"^\n" +
	"\x10WebSocketMessage\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.proto.websocket.MessageHeaderR\x06header\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\",\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"$\n" +
	"\fLoginMessage\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0f\n" +
	"\rLogoutMessage\"F\n" +
	"\x0fJoinRoomMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10LeaveRoomMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"U\n" +
	"\x11GameActionMessage\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vaction_data\x18\x02 \x01(\fR\n" +
	"actionData\"a\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tchat_type\x18\x01 \x01(\x05R\bchatType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x05R\btargetId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"(\n" +
	"\rUserInfoQuery\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"]\n" +
	"\rRoomListQuery\x12\x1b\n" +
	"\tgame_type\x18\x01 \x01(\tR\bgameType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x87\x01\n" +
	"\rGameStatePush\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vgame_status\x18\x02 \x01(\x05R\n" +
	"gameStatus\x12\x1b\n" +
	"\tgame_data\x18\x03 \x01(\fR\bgameData\x12\x1f\n" +
	"\vupdate_time\x18\x04 \x01(\x03R\n" +
	"updateTime\"\xc6\x01\n" +
	"\fRoomInfoPush\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12!\n" +
	"\fplayer_count\x18\x03 \x01(\x05R\vplayerCount\x12\x1f\n" +
	"\vmax_players\x18\x04 \x01(\x05R\n" +
	"maxPlayers\x12\x1f\n" +
	"\vroom_status\x18\x05 \x01(\x05R\n" +
	"roomStatus\x12\x1b\n" +
	"\troom_data\x18\x06 \x01(\fR\broomData\"z\n" +
	"\x0eUserUpdatePush\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1b\n" +
	"\tuser_data\x18\x04 \x01(\fR\buserData\"{\n" +
	"\x11SystemMessagePush\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\x05R\amsgType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\"\xc0\x01\n" +
	"\x0fChatMessagePush\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12\x1b\n" +
	"\tchat_type\x18\x03 \x01(\x05R\bchatType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x05R\btargetId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tsend_time\x18\x06 \x01(\x03R\bsendTime\"\xab\x01\n" +
	"\x10BroadcastMessage\x12!\n" +
	"\fbroadcast_id\x18\x01 \x01(\tR\vbroadcastId\x12%\n" +
	"\x0ebroadcast_type\x18\x02 \x01(\x05R\rbroadcastType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x05 \x01(\fR\textraData\"a\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x15\n" +
	"\x06msg_id\x18\x04 \x01(\tR\x05msgId\"\x95\x01\n" +
	"\x10RoomListResponse\x12/\n" +
	"\x05rooms\x18\x01 \x03(\v2\x19.proto.websocket.RoomInfoR\x05rooms\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xe3\x01\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1b\n" +
	"\tgame_type\x18\x03 \x01(\tR\bgameType\x12!\n" +
	"\fplayer_count\x18\x04 \x01(\x05R\vplayerCount\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\x12\x1f\n" +
	"\vroom_status\x18\x06 \x01(\x05R\n" +
	"roomStatus\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\tR\n" +
	"createTime*\xce\x02\n" +
	"\vMessageType\x12\x11\n" +
	"\rMSG_HEARTBEAT\x10\x00\x12\r\n" +
	"\tMSG_LOGIN\x10\x01\x12\x0e\n" +
	"\n" +
	"MSG_LOGOUT\x10\x02\x12\x11\n" +
	"\rMSG_JOIN_ROOM\x10\x03\x12\x12\n" +
	"\x0eMSG_LEAVE_ROOM\x10\x04\x12\x13\n" +
	"\x0fMSG_GAME_ACTION\x10\x05\x12\f\n" +
	"\bMSG_CHAT\x10\x06\x12\x17\n" +
	"\x13MSG_USER_INFO_QUERY\x10\a\x12\x17\n" +
	"\x13MSG_ROOM_LIST_QUERY\x10\b\x12\x17\n" +
	"\x13MSG_PUSH_GAME_STATE\x10d\x12\x16\n" +
	"\x12MSG_PUSH_ROOM_INFO\x10e\x12\x18\n" +
	"\x14MSG_PUSH_USER_UPDATE\x10f\x12\x17\n" +
	"\x13MSG_PUSH_SYSTEM_MSG\x10g\x12\x15\n" +
	"\x11MSG_PUSH_CHAT_MSG\x10h\x12\x16\n" +
	"\x12MSG_PUSH_BROADCAST\x10iB\rZ\v./websocketb\x06proto3"

var (
	file_proto_websocket_proto_rawDescOnce sync.Once
	file_proto_websocket_proto_rawDescData []byte
)

func file_proto_websocket_proto_rawDescGZIP() []byte {
	file_proto_websocket_proto_rawDescOnce.Do(func() {
		file_proto_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_websocket_proto_rawDesc), len(file_proto_websocket_proto_rawDesc)))
	})
	return file_proto_websocket_proto_rawDescData
}

var file_proto_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_websocket_proto_goTypes = []any{
	(MessageType)(0),          // 0: proto.websocket.MessageType
	(*MessageHeader)(nil),     // 1: proto.websocket.MessageHeader
	(*WebSocketMessage)(nil),  // 2: proto.websocket.WebSocketMessage
	(*Heartbeat)(nil),         // 3: proto.websocket.Heartbeat
	(*LoginMessage)(nil),      // 4: proto.websocket.LoginMessage
	(*LogoutMessage)(nil),     // 5: proto.websocket.LogoutMessage
	(*JoinRoomMessage)(nil),   // 6: proto.websocket.JoinRoomMessage
	(*LeaveRoomMessage)(nil),  // 7: proto.websocket.LeaveRoomMessage
	(*GameActionMessage)(nil), // 8: proto.websocket.GameActionMessage
	(*ChatMessage)(nil),       // 9: proto.websocket.ChatMessage
	(*UserInfoQuery)(nil),     // 10: proto.websocket.UserInfoQuery
	(*RoomListQuery)(nil),     // 11: proto.websocket.RoomListQuery
	(*GameStatePush)(nil),     // 12: proto.websocket.GameStatePush
	(*RoomInfoPush)(nil),      // 13: proto.websocket.RoomInfoPush
	(*UserUpdatePush)(nil),    // 14: proto.websocket.UserUpdatePush
	(*SystemMessagePush)(nil), // 15: proto.websocket.SystemMessagePush
	(*ChatMessagePush)(nil),   // 16: proto.websocket.ChatMessagePush
	(*BroadcastMessage)(nil),  // 17: proto.websocket.BroadcastMessage
	(*CommonResponse)(nil),    // 18: proto.websocket.CommonResponse
	(*RoomListResponse)(nil),  // 19: proto.websocket.RoomListResponse
	(*RoomInfo)(nil),          // 20: proto.websocket.RoomInfo
}
var file_proto_websocket_proto_depIdxs = []int32{
	0,  // 0: proto.websocket.MessageHeader.msg_type:type_name -> proto.websocket.MessageType
	1,  // 1: proto.websocket.WebSocketMessage.header:type_name -> proto.websocket.MessageHeader
	20, // 2: proto.websocket.RoomListResponse.rooms:type_name -> proto.websocket.RoomInfo
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_websocket_proto_init() }
func file_proto_websocket_proto_init() {
	if File_proto_websocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_websocket_proto_rawDesc), len(file_proto_websocket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_websocket_proto_goTypes,
		DependencyIndexes: file_proto_websocket_proto_depIdxs,
		EnumInfos:         file_proto_websocket_proto_enumTypes,
		MessageInfos:      file_proto_websocket_proto_msgTypes,
	}.Build()
	File_proto_websocket_proto = out.File
	file_proto_websocket_proto_goTypes = nil
	file_proto_websocket_proto_depIdxs = nil
}
